x=int(input("Enter x: "))
y=int(input("Enter y: "))
print("-------Arithmetic Operators-------")
print("Addition (x+y): ",x+y)
print("Subtraction (x-y): ",x-y)
print("Multiplication (x*y): ",x*y)
print("Exponential (x**y): ",x**y)
print("Division (x/y): ",x/y)
print("Floor division (Integer division) (x//y): ",x//y)
print("Modulus (x%y): ",x%y)
